-- if you wanna add subdirectory imports then use " . " instead of " / "
require("base")
require("plugins")
require("maps")
require("after.nvim-tree")
require("after.material")
require("after.lualine")
require("after.lsp.nvim-cmp")
require("after.lsp.mason")
require("after.hop")
require("after.lsp.lspsaga")
require("after.lsp.lspconfig")
require("after.lsp.null_ls")
require("after.lsp.autoclose")
require("after.lsp.treesitter")
require("after.telescope")
